/* La Bistro Billing — shared cloud sales sync (Supabase REST) */
(()=>{'use strict';const B=window.LB;
function configured(){return !!(B?.cloud?.url&&B?.cloud?.key)}
function headers(){return{apikey:B.cloud.key,Authorization:'Bearer '+B.cloud.key,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'}}
function endpoint(){return B.cloud.url.replace(/\/$/,'')+'/rest/v1/la_bistro_store'}
function mergeSales(local,remote){const m=new Map();[...(remote||[]),...(local||[])].forEach(x=>{if(x?.id)m.set(x.id,x)});return [...m.values()].sort((a,b)=>String(a.at).localeCompare(String(b.at)))}
function mergeCustomers(local,remote){const out={...(remote||{})};for(const [k,v] of Object.entries(local||{})){const r=out[k];if(!r){out[k]=v;continue}out[k]={...r,...v,total:Math.max(Number(r.total||0),Number(v.total||0)),visits:Math.max(Number(r.visits||0),Number(v.visits||0)),lastAt:String(r.lastAt||'')>String(v.lastAt||'')?r.lastAt:v.lastAt}}return out}
async function getRemote(){if(!configured())return null;const r=await fetch(endpoint()+'?store_id=eq.'+encodeURIComponent(B.cloud.store||'la-bistro'),{headers:headers()});if(!r.ok)throw Error(await r.text());const a=await r.json();return a[0]||null}
async function push(){if(!configured())return false;try{const remote=await getRemote();const rp=remote?.payload||{};const payload={sales:mergeSales(B.sales,rp.sales),stock:{...(rp.stock||{}),...(B.stock||{})},customers:mergeCustomers(B.customers,rp.customers),customItems:B.customItems?.length?B.customItems:(rp.customItems||[])};B.sales=payload.sales;B.customers=payload.customers;B.stock=payload.stock;B.customItems=payload.customItems;B.save('lb_sales_v2',B.sales);B.save('lb_stock_v2',B.stock);B.save('lb_customers_v2',B.customers);B.save('lb_custom_menu_v2',B.customItems);const r=await fetch(endpoint(),{method:'POST',headers:headers(),body:JSON.stringify({store_id:B.cloud.store||'la-bistro',payload,updated_at:new Date().toISOString()})});if(!r.ok)throw Error(await r.text());return true}catch(e){console.warn('Cloud push:',e);return false}}
async function pull(silent=false){if(!configured())return false;try{const row=await getRemote();const d=row?.payload;if(!d)return false;B.sales=mergeSales(B.sales,d.sales);B.stock={...(B.stock||{}),...(d.stock||{})};B.customers=mergeCustomers(B.customers,d.customers);B.customItems=(B.customItems?.length?B.customItems:(d.customItems||[]));B.save('lb_sales_v2',B.sales);B.save('lb_stock_v2',B.stock);B.save('lb_customers_v2',B.customers);B.save('lb_custom_menu_v2',B.customItems);window.renderMenu?.();window.renderCart?.();if(!silent)B.toast('Cloud data synced');return true}catch(e){if(!silent)B.toast('Cloud sync error');console.warn('Cloud pull:',e);return false}}
window.lbCloudPush=push;window.lbCloudPull=pull;
window.saveLBCloud=async()=>{B.cloud={url:clUrl.value.trim().replace(/\/$/,''),key:clKey.value.trim(),store:clStore.value.trim()||'la-bistro'};B.save('lb_cloud_v2',B.cloud);if(!configured())return B.toast('Enter Supabase URL and publishable key');const ok=await pull(true);if(ok)await push();B.toast(ok?'Cloud connected':'Check Supabase settings')};
window.renderLBCloud=()=>{lbContent.innerHTML=`<h3>☁️ Shared Sales — 10 Phones</h3><p class=lbNote>All phones must use the same Supabase project and Store ID. Use a Supabase publishable key in this browser app; never use a secret/service-role key.</p><label>Supabase Project URL<input class=lbInput id="clUrl" value="${B.esc(B.cloud.url)}" placeholder="https://xxxxx.supabase.co"></label><label>Publishable key<input class=lbInput id="clKey" value="${B.esc(B.cloud.key)}" placeholder="sb_publishable_..."></label><label>Store ID<input class=lbInput id="clStore" value="${B.esc(B.cloud.store||'la-bistro')}" placeholder="la-bistro"></label><div class=lbActions><button onclick="saveLBCloud()">Connect / Save</button><button onclick="lbCloudPull()">Sync Now</button></div><h4>Run once in Supabase SQL Editor</h4><textarea class=lbCode readonly>create table if not exists public.la_bistro_store (store_id text primary key,payload jsonb not null,updated_at timestamptz default now());
alter table public.la_bistro_store enable row level security;
grant select, insert, update on public.la_bistro_store to anon, authenticated;
drop policy if exists "la bistro read" on public.la_bistro_store;
drop policy if exists "la bistro insert" on public.la_bistro_store;
drop policy if exists "la bistro update" on public.la_bistro_store;
create policy "la bistro read" on public.la_bistro_store for select to anon, authenticated using (true);
create policy "la bistro insert" on public.la_bistro_store for insert to anon, authenticated with check (true);
create policy "la bistro update" on public.la_bistro_store for update to anon, authenticated using (true) with check (true);</textarea><p class=lbNote>After connecting, the app automatically syncs sales. Keep the same Store ID on all phones.</p>`};
window.addEventListener('load',()=>setTimeout(()=>{if(configured()){pull(true);setInterval(()=>pull(true),15000)}},1200));
})();
