/* La Bistro POS — fresh single quantity + billing system. Menu data is loaded from the existing approved menu script. */
(()=>{
'use strict';
const cart = Object.create(null);
const keyFor = (en,bn,price)=>`${en}||${bn}||${price}`;
const esc = s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money = n=>'₹'+Number(n||0).toFixed(2).replace(/\.00$/,'');
function itemInfo(card){const en=(card.querySelector('.en')?.textContent||'').trim();const bn=(card.querySelector('.bn')?.textContent||'').trim();const price=Number((card.querySelector('.price')?.textContent||'').replace(/[^0-9.]/g,''))||0;return {en,bn,price,key:keyFor(en,bn,price)}}
function qty(info){return cart[info.key]?.qty||0}
function setQty(info,q){q=Math.max(0,Math.floor(Number(q)||0));if(q===0)delete cart[info.key];else cart[info.key]={...info,qty:q};updateMenuControls();renderFreshBill()}
function add(info){setQty(info,qty(info)+1)}
function sub(info){setQty(info,qty(info)-1)}
function injectMenuControls(){const panel=document.getElementById('menuPanel');if(!panel)return;panel.querySelectorAll('.item').forEach(card=>{const info=itemInfo(card);if(!info.en)return;let c=card.querySelector('.fresh-qty-controls');if(!c){c=document.createElement('span');c.className='fresh-qty-controls';c.innerHTML='<span class="fresh-minus">−</span><b class="fresh-count">0</b><span class="fresh-plus">+</span>';card.appendChild(c)}c.querySelector('.fresh-count').textContent=qty(info)})}
function updateMenuControls(){const panel=document.getElementById('menuPanel');if(!panel)return;panel.querySelectorAll('.item').forEach(card=>{const info=itemInfo(card),c=card.querySelector('.fresh-qty-controls');if(c)c.querySelector('.fresh-count').textContent=qty(info)})}
function totals(){let gross=0;Object.values(cart).forEach(i=>gross+=i.price*i.qty);const discountPct=Math.max(0,Math.min(100,Number(document.getElementById('freshDiscount')?.value)||0));const discount=gross*discountPct/100;const taxable=gross-discount;const gstPct=Math.max(0,Number(document.getElementById('freshGst')?.value)||0);const gst=taxable*gstPct/100;return {gross,discountPct,discount,taxable,gstPct,gst,total:taxable+gst}}
function renderFreshBill(){const host=document.getElementById('fresh-billing');if(!host)return;const t=totals();const rows=Object.values(cart).map(i=>`<div class="fresh-row"><div class="fresh-qty"><span class="fresh-bill-minus" data-key="${esc(i.key)}">−</span><b>${i.qty}</b><span class="fresh-bill-plus" data-key="${esc(i.key)}">+</span></div><div class="fresh-item"><b>${esc(i.en)}</b><small>${esc(i.bn)}</small></div><div class="fresh-price">${money(i.price)}</div><div class="fresh-total">${money(i.price*i.qty)}</div></div>`).join('');host.innerHTML=`<div class="fresh-card"><h2>Current Bill / বর্তমান বিল</h2><div class="fresh-head"><span>Qty<br>পরিমাণ</span><span>Item / আইটেম</span><span>Price<br>দাম</span><span>Total<br>মোট</span></div><div class="fresh-rows">${rows||'<div class="fresh-empty">No items / কোনো আইটেম নেই</div>'}</div><div class="fresh-summary"><div><span>Subtotal / মোট</span><b>${money(t.gross)}</b></div><div class="fresh-input-line"><span>Discount / ছাড়</span><label><b>Discount / ছাড়</b><input id="freshDiscount" type="number" min="0" max="100" step="0.1" value="${t.discountPct}"><em>%</em><b>${money(t.discount)}</b></label></div><div class="fresh-input-line"><span>GST / জিএসটি</span><label><input id="freshGst" type="number" min="0" step="0.1" value="${t.gstPct}"><em>%</em><b>${money(t.gst)}</b></label></div><div class="fresh-total-line"><span>TOTAL / সর্বমোট</span><b>${money(t.total)}</b></div></div><div class="fresh-payments"><button class="fresh-pay active" data-pay="Cash">Cash / নগদ</button><button class="fresh-pay" data-pay="UPI">UPI</button><button class="fresh-pay" data-pay="Card">Card</button></div><div class="fresh-actions"><button id="freshPrint">PRINT BILL / বিল প্রিন্ট</button><button id="freshWhatsApp">WHATSAPP BILL / হোয়াটসঅ্যাপ বিল</button></div><div class="fresh-note">One tap = quantity 1. Every additional tap increases quantity. Use − to reduce it.</div></div>`;host.querySelector('#freshDiscount').oninput=renderFreshBill;host.querySelector('#freshGst').oninput=renderFreshBill;host.querySelectorAll('.fresh-bill-minus').forEach(b=>b.onclick=()=>{const i=cart[b.dataset.key];if(i)setQty(i,i.qty-1)});host.querySelectorAll('.fresh-bill-plus').forEach(b=>b.onclick=()=>{const i=cart[b.dataset.key];if(i)setQty(i,i.qty+1)});host.querySelectorAll('.fresh-pay').forEach(b=>b.onclick=()=>{host.querySelectorAll('.fresh-pay').forEach(x=>x.classList.remove('active'));b.classList.add('active')});host.querySelector('#freshPrint').onclick=printBill;host.querySelector('#freshWhatsApp').onclick=whatsAppBill}
function printBill(){if(!Object.keys(cart).length){alert('Add items first / আগে আইটেম যোগ করুন');return}const t=totals();const payment=document.querySelector('.fresh-pay.active')?.dataset.pay||'Cash';const rows=Object.values(cart).map(i=>`<tr><td>${i.qty}</td><td>${esc(i.en)}<br>${esc(i.bn)}</td><td>${money(i.price*i.qty)}</td></tr>`).join('');const h=`<!doctype html><html><head><meta charset="utf-8"><style>body{font:11px Arial;width:72mm;margin:auto;color:#000}h2{text-align:center}table{width:100%;border-collapse:collapse}td{padding:4px 0;border-bottom:1px dotted #999}.r{text-align:right}.big{font-size:16px;font-weight:bold}</style></head><body><h2>LA BISTRO</h2><div style="text-align:center">Multi Cuisine Family Restaurant • লা বিস্ট্রো<br>${new Date().toLocaleString('en-IN')}</div><hr><table><tr><th>Qty</th><th>Item</th><th>Amount</th></tr>${rows}</table><hr><div class="r">Subtotal: ${money(t.gross)}<br>Discount (${t.discountPct}%): -${money(t.discount)}<br>GST (${t.gstPct}%): ${money(t.gst)}<br><span class="big">TOTAL: ${money(t.total)}</span></div><p>Payment: ${esc(payment)}</p><center>Thank you / ধন্যবাদ</center><script>onload=()=>setTimeout(()=>print(),250)<\/script></body></html>`;const w=window.open('','_blank');if(!w){alert('Please allow pop-ups for printing');return}w.document.write(h);w.document.close()}
function whatsAppBill(){if(!Object.keys(cart).length){alert('Add items first / আগে আইটেম যোগ করুন');return}const t=totals();let msg='LA BISTRO / লা বিস্ট্রো\n';Object.values(cart).forEach(i=>msg+=`${i.en} x${i.qty} = ${money(i.price*i.qty)}\n`);msg+=`Subtotal: ${money(t.gross)}\nDiscount: ${money(t.discount)}\nGST: ${money(t.gst)}\nTOTAL: ${money(t.total)}`;window.open('https://wa.me/?text='+encodeURIComponent(msg),'_blank')}
function install(){let host=document.getElementById('fresh-billing');if(!host){host=document.createElement('div');host.id='fresh-billing';const old=document.querySelector('.cart');if(old){old.style.display='none';old.parentNode.insertBefore(host,old)}else document.body.appendChild(host)}injectMenuControls();renderFreshBill()}
document.addEventListener('click',e=>{const control=e.target.closest?.('.fresh-qty-controls');if(control){e.preventDefault();e.stopPropagation();const card=control.closest('.item'),info=card&&itemInfo(card);if(!info)return;if(e.target.closest('.fresh-minus'))sub(info);else if(e.target.closest('.fresh-plus'))add(info);return}const card=e.target.closest?.('#menuPanel .item');if(card){e.preventDefault();e.stopPropagation();const info=itemInfo(card);if(info.en)add(info)}},true);
function loadMenu(){if(window.__freshMenuLoaded){install();return}window.__freshMenuLoaded=true;const s=document.createElement('script');s.src='./lb-repair-v3.js?v=fresh1';s.onload=()=>{try{window.injectLBMenu?.();window.renderMenu?.()}catch(e){}setTimeout(install,100);setTimeout(install,500);setTimeout(install,1200)};s.onerror=()=>setTimeout(install,500);document.head.appendChild(s)}
const style=document.createElement('style');style.textContent=`.fresh-qty-controls{position:absolute;right:7px;top:7px;display:flex;align-items:center;gap:5px;background:#fff;border:1px solid #c9a74f;border-radius:8px;padding:2px 4px;z-index:5;color:#111!important}.fresh-qty-controls span{display:inline-flex;align-items:center;justify-content:center;min-width:25px;height:25px;border-radius:6px;border:1px solid #c9a74f;background:#fff;font-size:18px;line-height:1;cursor:pointer}.fresh-qty-controls b{min-width:18px;text-align:center;color:#111}.fresh-card{background:#fff;border:1px solid #c9a74f;border-radius:11px;padding:11px;margin:11px 0;color:#111}.fresh-card h2{margin:0 0 12px;font-family:'Playfair Display',serif;font-size:25px}.fresh-head,.fresh-row{display:grid;grid-template-columns:78px 1fr 70px 78px;gap:7px;align-items:center}.fresh-head{font-weight:800;border-bottom:1px solid #aaa;padding:6px 2px;font-size:12px}.fresh-row{padding:8px 0;border-bottom:1px dashed #bbb}.fresh-qty{display:flex;align-items:center;justify-content:center;gap:5px}.fresh-qty span{width:27px;height:27px;border:1px solid #c9a74f;border-radius:6px;display:flex;align-items:center;justify-content:center;cursor:pointer}.fresh-qty b{text-align:center;min-width:18px}.fresh-item b{display:block;font-size:15px}.fresh-item small{display:block;font-size:12px;color:#444}.fresh-price,.fresh-total{text-align:right;font-weight:800}.fresh-empty{text-align:center;padding:25px;color:#777}.fresh-summary{margin-top:8px;border-top:1px solid #8f722f}.fresh-summary>div{display:flex;justify-content:space-between;align-items:center;padding:6px 0;font-size:16px}.fresh-input-line label{display:flex;align-items:center;gap:5px}.fresh-input-line input{width:70px;padding:8px;border:1px solid #ccc;border-radius:8px;font-size:16px}.fresh-input-line em{font-style:normal}.fresh-total-line{font-size:21px!important;font-weight:800;border-top:1px solid #8f722f;margin-top:4px}.fresh-payments,.fresh-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:8px}.fresh-actions{grid-template-columns:1fr 1fr}.fresh-pay,.fresh-actions button{padding:10px;border:1px solid #c9a74f;border-radius:8px;background:#fff;color:#111;font-weight:700}.fresh-pay.active,.fresh-actions button:first-child{background:#d9a62e}.fresh-note{font-size:11px;color:#666;margin-top:7px}@media(max-width:560px){.fresh-head,.fresh-row{grid-template-columns:72px 1fr 60px 68px}.fresh-card{margin:9px 0}.fresh-card h2{font-size:24px}.fresh-item b{font-size:14px}}`;
document.head.appendChild(style);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',loadMenu);else loadMenu();window.addEventListener('load',()=>setTimeout(loadMenu,150));
})();
