(()=>{
'use strict';
const money=n=>'₹'+Number(n||0).toFixed(2).replace(/\.00$/,'');
function getCart(){try{return cart||{};}catch(e){return window.cart||{};}}
function findEntry(en,bn){const c=getCart();for(const k of Object.keys(c)){const v=c[k];if(v&&Array.isArray(v.item)&&String(v.item[0]).trim()===en&&String(v.item[1]).trim()===bn)return [k,v];}return null;}
function setQty(en,bn,price,delta){const c=getCart();let f=findEntry(en,bn);let key=f?f[0]:(en+'|'+bn);let v=f?f[1]:{item:[en,bn,Number(price)],qty:0};v.qty=Math.max(0,Number(v.qty||0)+delta);if(v.qty===0)delete c[key];else c[key]=v;try{renderCart();}catch(e){}refresh();}
function cardData(card){return {en:(card.querySelector('.en')?.textContent||'').trim(),bn:(card.querySelector('.bn')?.textContent||'').trim(),price:Number((card.querySelector('.price')?.textContent||'').replace(/[^0-9.]/g,''))||0};}
function installCards(){document.querySelectorAll('#menuPanel .item').forEach(card=>{const d=cardData(card);if(!d.en||card.dataset.qf)return;card.dataset.qf='1';let controls=document.createElement('div');controls.className='qf-menu-controls';controls.innerHTML='<button type="button" class="qf-minus">−</button><b class="qf-count">0</b><button type="button" class="qf-plus">+</button>';card.appendChild(controls);controls.addEventListener('click',e=>{e.stopPropagation();e.preventDefault();if(e.target.closest('.qf-minus'))setQty(d.en,d.bn,d.price,-1);if(e.target.closest('.qf-plus'))setQty(d.en,d.bn,d.price,1);});});refresh();}
function refresh(){const c=getCart();document.querySelectorAll('#menuPanel .item').forEach(card=>{const d=cardData(card),f=findEntry(d.en,d.bn),q=f?Number(f[1].qty||0):0;const n=card.querySelector('.qf-count');if(n)n.textContent=q;card.classList.toggle('selected',q>0);let badge=card.querySelector('.qty');if(badge){badge.textContent=q>0?q:'';badge.style.display=q>0?'flex':'none';}});renderBill();}
function renderBill(){const box=document.getElementById('cartItems');if(!box)return;const c=getCart();let sub=0;let html='';for(const k of Object.keys(c)){const v=c[k];if(!v||!Array.isArray(v.item)||Number(v.qty||0)<=0)continue;const en=String(v.item[0]),bn=String(v.item[1]),price=Number(v.item[2]||0),q=Number(v.qty||0),line=price*q;sub+=line;html+=`<div class="cart-row"><div class="bill-line"><div class="bill-qty">${q}</div><div class="bill-item"><div class="cart-name">${esc(en)}</div><div class="cart-bn">${esc(bn)}</div><div class="row-controls"><button type="button" class="small qf-bill-minus" data-key="${escAttr(k)}">−</button><b>${q}</b><button type="button" class="small qf-bill-plus" data-key="${escAttr(k)}">+</button></div></div><div class="bill-price">${money(price)}</div><div class="bill-total">${money(line)}</div></div></div>`;}
box.innerHTML=html||'<div class="empty">No items / কোনো আইটেম নেই</div>';
box.querySelectorAll('.qf-bill-minus').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();changeKey(b.dataset.key,-1)});
box.querySelectorAll('.qf-bill-plus').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();changeKey(b.dataset.key,1)});
const pct=Math.max(0,Math.min(100,Number(document.getElementById('lbDiscountPct')?.value||0)));const discount=sub*pct/100;const gstRate=Math.max(0,Number(document.getElementById('gst')?.value||0));const taxable=Math.max(0,sub-discount);const gst=taxable*gstRate/100;const total=taxable+gst;setText('subtotal',money(sub));setText('discount',money(discount));setText('totalDiscount',money(discount));setText('lbDiscountAmt',money(discount));setText('tax',money(gst));setText('total',money(total));setText('grandTotal',money(total));}
function changeKey(key,delta){const c=getCart();if(!c[key])return;c[key].qty=Math.max(0,Number(c[key].qty||0)+delta);if(c[key].qty===0)delete c[key];try{renderCart();}catch(e){}refresh();}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}function escAttr(s){return esc(s).replace(/\s/g,'&#32;')}function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v;}
function hook(){installCards();const disc=document.getElementById('lbDiscountPct');if(disc&&!disc.dataset.qf){disc.dataset.qf='1';disc.addEventListener('input',renderBill)}const gst=document.getElementById('gst');if(gst&&!gst.dataset.qf){gst.dataset.qf='1';gst.addEventListener('input',renderBill)}if(!window.__qfMenuClick){window.__qfMenuClick=1;document.addEventListener('click',e=>{const card=e.target.closest?.('#menuPanel .item');if(!card||e.target.closest('.qf-menu-controls'))return;e.preventDefault();e.stopImmediatePropagation();const d=cardData(card);setQty(d.en,d.bn,d.price,1);},true);}}
const style=document.createElement('style');style.textContent='.qf-menu-controls{position:absolute;right:6px;top:6px;display:flex;align-items:center;gap:4px;z-index:5}.qf-menu-controls button{width:30px;height:30px;border:1px solid #b8953b;border-radius:6px;background:#fff;color:#111;font-size:20px;line-height:26px;padding:0;cursor:pointer}.qf-menu-controls b{min-width:20px;text-align:center;color:#111}.qf-menu-controls+.qty{display:none!important}.qf-bill-minus,.qf-bill-plus{min-width:28px;font-size:17px}.cart-row{color:#111}';document.head.appendChild(style);
let n=0;const timer=setInterval(()=>{hook();if(++n>30)clearInterval(timer)},500);window.addEventListener('load',hook);})();